name: build

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Attempt publish
      run: |
        cd src
        dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained true -p:PublishReadyToRun=true
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ./src/bin/Release/net7.0/win-x64/HardwareSensorsToMQTT.exe
